# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='name')),
                ('url', models.CharField(max_length=100, verbose_name='telegram url')),
                ('description', models.TextField(verbose_name='channel description')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_channel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='GemBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='name')),
                ('price', models.PositiveIntegerField(default=100, verbose_name='price')),
                ('sku', models.IntegerField(default=100, unique=True, verbose_name='sku')),
            ],
            options={
                'db_table': 'game_box',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField(default=100, unique=True)),
                ('gem_quantity', models.IntegerField(default=100, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
